#!/usr/bin/env node
/**
 * clean.js — Zero-dependency pre-build cache cleaner.
 *
 * Clears stale build artifacts before every production build so that
 * `npm run build` always outputs fully fresh content.
 *
 * Preserved (fast, safe):
 *   .svelte-kit/generated   — SvelteKit type-gen (regenerated by svelte-kit sync)
 *   .svelte-kit/tsconfig.json
 *   node_modules/.vite      — dependency pre-bundling cache (rarely changes)
 *
 * Removed (stale, rebuilt):
 *   .svelte-kit/output      — SSR/client bundle from last build
 *   .svelte-kit/adapter-node
 *   build/                  — node adapter output folder
 */

import { rmSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const targets = [
  resolve(root, '.svelte-kit', 'output'),
  resolve(root, '.svelte-kit', 'adapter-node'),
  resolve(root, 'build'),
];

console.log('🧹 Pre-build clean — removing stale artifacts...');
for (const dir of targets) {
  if (existsSync(dir)) {
    rmSync(dir, { recursive: true, force: true });
    console.log(`  ✓ removed ${dir.replace(root, '.')}`);
  } else {
    console.log(`  – skipped ${dir.replace(root, '.')} (not found)`);
  }
}
console.log('✅ Clean complete. Starting fresh build...\n');
